# Generated by Django 6.0.5 on 2026-05-26 18:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_user_is_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="PendingDeposit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount_ton", models.FloatField()),
                ("boc", models.TextField()),
                ("is_processed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_deposits",
                        to="core.user",
                    ),
                ),
            ],
        ),
    ]
